// import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import UserProviderForPage from "@/lib/UserProviderForPage";
// import "../cron";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let user = await UserProviderForPage();
  let safeuser = user ? JSON.parse(JSON.stringify(user)) : null;
  console.log("this is user in layout", user);
  const currentTheme = safeuser?.theme || "light";

  return (
    // 2. FIXED: Feed the theme directly to the HTML element class string
    <html lang="en" className={currentTheme === "dark" ? "dark" : ""}>
      <body>
        <Header user={safeuser}></Header>
        <div className=" page min-h-screen">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
