// import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import UserProviderForPage from "@/lib/UserProviderForPage";
import NextTopLoader from "nextjs-toploader"; // 1. Import the loader
// import "../cron";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let user = await UserProviderForPage();
  let safeuser = user ? JSON.parse(JSON.stringify(user)) : null;
  console.log("this is user in layout", user);
  const currentTheme = safeuser?.theme || "light";

  return (
    <html lang="en" className={currentTheme === "dark" ? "dark" : ""}>
      <body>
        {/* 2. Add the loader component here */}
        <NextTopLoader
          color="#7c3aed" // You can change this to match your brand color
          showSpinner={false}
          zIndex={99999}
        />

        <Header user={safeuser}></Header>
        <div className=" page min-h-screen">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
